version: 3

tasks:
  start-infra:
    cmd: docker compose -f ./containers/NiroBank.yml up -d

  stop-infra:
    cmd: docker compose -f ./containers/NiroBank.yml down

  restart-infra:
    cmds:
      - task: stop-infra
      - cmd: timeout 1
      - task: start-infra