name: "AuthServer Infrastructure"

services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=auth-server"
      - "POSTGRES_PASSWORD=auth-server-password"
      - "POSTGRES_DB=auth-db"
      - "PGUSER=auth-server"
      - "PGDATABASE=auth-db"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', "-U", "auth-server", "-d", "auth-db"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  auth-cache:
    image: redis:alpine
    container_name: auth-cache
    ports:
      - "16379:6379"
    volumes:
      - ./auth-cache/data:/root/redis
      - ./auth-cache/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - "REDIS_PASSWORD=auth-cache-password"
      - "REDIS_PORT=6379"
      - "REDIS_DATABASE=16"