name: 'NiroBank-Infra'

services:
  user-service-db:
    image: postgres:16-alpine
    container_name: user-service-db
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=user-service"
      - "POSTGRES_PASSWORD=user-service-password"
      - "POSTGRES_DB=user-service-db"
      - "PGUSER=user-service"
      - "PGDATABASE=user-service-db"
    healthcheck:
      test: "pg_isready -U user-service -d user-service-db"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s


#  auth-cache:
#    image: redis:alpine
#    container_name: auth-cache
#    ports:
#      - "16379:6379"
#    volumes:
#      - ./auth-cache/data:/root/redis
#      - ./auth-cache/redis.conf:/usr/local/etc/redis/redis.conf
#    environment:
#      - "REDIS_PASSWORD=auth-cache-password"
#      - "REDIS_PORT=6379"
#      - "REDIS_DATABASE=16"