name: 'NiroBank-Infra'

services:
  user-service-db:
    image: postgres:16-alpine
    container_name: user-service-db
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=user-service"
      - "POSTGRES_PASSWORD=user-service-password"
      - "POSTGRES_DB=user-service-db"
      - "PGUSER=user-service"
      - "PGDATABASE=user-service-db"
    healthcheck:
      test: "pg_isready -U user-service -d user-service-db"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles:
      - "user"
      - "all"


  token_service_db:
    image: postgres:16-alpine
    container_name: token_service_db
    ports:
      - "25432:5432"
    environment:
      - "POSTGRES_USER=token_service_username"
      - "POSTGRES_PASSWORD=token_service_password"
      - "POSTGRES_DB=token_service_db"
      - "PGUSER=token_service_username"
      - "PGDATABASE=token_service_db"
    healthcheck:
      test: "pg_isready -U token_service_username -d token_service_db"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles:
      - "token"
      - "all"

  auth_service_db:
    image: postgres:16-alpine
    container_name: auth_service_db
    ports:
      - "35432:5432"
    environment:
      - "POSTGRES_USER=auth_service_username"
      - "POSTGRES_PASSWORD=auth_service_password"
      - "POSTGRES_DB=auth_service_db"
      - "PGUSER=auth_service_username"
      - "PGDATABASE=auth_service_db"
    healthcheck:
      test: "pg_isready -U auth_service_username -d auth_service_db"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles:
      - "auth"
      - "all"

  account_service_db:
    image: postgres:16-alpine
    container_name: account_service_db
    ports:
      - "45432:5432"
    environment:
      - "POSTGRES_USER=account_service_username"
      - "POSTGRES_PASSWORD=account_service_password"
      - "POSTGRES_DB=account_service_db"
      - "PGUSER=account_service_username"
      - "PGDATABASE=account_service_db"
    healthcheck:
      test: "pg_isready -U account_service_username -d account_service_db"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles:
      - "account"
      - "all"


#  auth-cache:
#    image: redis:alpine
#    container_name: auth-cache
#    ports:
#      - "16379:6379"
#    volumes:
#      - ./auth-cache/data:/root/redis
#      - ./auth-cache/redis.conf:/usr/local/etc/redis/redis.conf
#    environment:
#      - "REDIS_PASSWORD=auth-cache-password"
#      - "REDIS_PORT=6379"
#      - "REDIS_DATABASE=16"